version: "3"
services:

  mysqldb:
    container_name: my-mysql
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"

  rest-service:
    restart: always
    image: rest-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
